export interface ImageAttachment {
  id: string;
  file: File;
  preview: string;
  name: string;
  size: number;
  type: string;
  uploadedAt: Date;
}

export type ProductMode =
  | 'SaaS Product'
  | 'AI Product'
  | 'Mobile App'
  | 'Feature Enhancement';

export interface PrdInput {
  productName: string;
  targetAudience: string;
  problemStatement: string;
  proposedSolution: string;
  coreFeatures: string;
  keyFeatures: string;
  businessGoals: string;
  successMetrics: string;
  futureFeatures: string;
  techStack: string;
  constraints: string;
  timeline: string;
  budget: string;
  productMode: ProductMode;
  currentState?: string;
  proposedChanges?: string;
  productIdeaImages?: ImageAttachment[];
}

export const DEFAULT_PRD_INPUT: PrdInput = {
  productName: '',
  targetAudience: '',
  problemStatement: '',
  proposedSolution: '',
  coreFeatures: '',
  keyFeatures: '',
  businessGoals: '',
  successMetrics: '',
  futureFeatures: '',
  techStack: '',
  constraints: '',
  timeline: '',
  budget: '',
  productMode: 'SaaS Product',
  currentState: '',
  proposedChanges: '',
  productIdeaImages: []
};

export const SECTION_FIELD_MAPPING: Record<string, Array<keyof PrdInput>> = {
  '1. Core Product Idea': [
    'productName',
    'problemStatement',
    'proposedSolution'
  ],
  '2. Enhancement Scope': ['currentState', 'proposedChanges'],
  '3. Audience & Market': ['targetAudience', 'businessGoals', 'successMetrics'],
  '4. Features & Scope': ['coreFeatures', 'keyFeatures', 'futureFeatures'],
  '5. Technical Details': ['techStack', 'constraints'],
  '6. Planning & Execution': ['timeline', 'budget', 'constraints']
};

export function generatePreviewMarkdown(inputs: PrdInput): string {
  return `
# ${inputs.productName || 'Product Name...'}

*This is a live preview of your input. The final PRD will be generated by AI based on these details.*

### Problem Statement
${inputs.problemStatement || '...'}

### Proposed Solution
${inputs.proposedSolution || '...'}

### Target Audience
${inputs.targetAudience || '...'}

### Core Features
${inputs.coreFeatures || '...'}
  `;
}

export function buildGenerationPrompt(inputs: PrdInput): string {
  // Build image context if images are provided
  let imageContext = '';
  if (inputs.productIdeaImages && inputs.productIdeaImages.length > 0) {
    imageContext =
      '\n\n**Visual Context:** The user has provided the following images to help illustrate the product concept:\n';
    inputs.productIdeaImages.forEach((img, index) => {
      imageContext += `\n${index + 1}. ${img.name} (${img.type})\n`;
      imageContext += `   [Image data included for context - may contain mockups, wireframes, diagrams, or reference photos]\n`;
    });
    imageContext +=
      "\nPlease consider these visual materials when writing the PRD. They provide important context about the user's vision for the product design, user interface, and functionality.";
  }

  const isEnhancement = inputs.productMode === 'Feature Enhancement';
  const enhancementSection = isEnhancement
    ? `
**Input Context: Feature Enhancement**
* Current State (Before): ${inputs.currentState || 'Not specified.'}
* Proposed Changes (After): ${inputs.proposedChanges || 'Not specified.'}
`
    : '';

  return `
You are an expert Senior Product Manager at a leading tech company. Your task is to write a highly detailed, comprehensive Product Requirements Document (PRD) for a **${inputs.productMode}**.

The PRD MUST strictly follow the exact 29-module structure outlined below. Expand on the provided user inputs to create a robust, development-ready document. Extrapolate intelligently where necessary. Use professional formatting, bullet points, tables, and bold text where appropriate.

**Input Context from User:**
* Product Name: ${inputs.productName}
* Product Category: ${inputs.productMode}
* Problem Statement: ${inputs.problemStatement}
* Proposed Solution: ${inputs.proposedSolution}
${enhancementSection}
* Target Audience: ${inputs.targetAudience}
* Business Goals: ${inputs.businessGoals}
* Success Metrics: ${inputs.successMetrics}
* Core Features: ${inputs.coreFeatures}
* Key Differentiators: ${inputs.keyFeatures}
* Future Features: ${inputs.futureFeatures}
* Tech Stack: ${inputs.techStack}
* Timeline: ${inputs.timeline}
* Budget: ${inputs.budget}
* Constraints: ${inputs.constraints}
${imageContext}

**REQUIRED PRD STRUCTURE (Generate content for ALL these sections explicitly using these exact Markdown headings):**

# ${inputs.productName || 'Product Requirements Document'}

## Executive Summary
*(Provide a concise, high-level overview of the product, its value proposition, target audience, and primary objective for this release.)*

## Project Overview
### Mission & Core Principles
*(Define the core mission of this product and 3-4 guiding principles for the development team.)*
### Problem Statement
*(Clearly articulate the exact pain points and problems the users are currently facing.)*
### Goals & Objectives
*(List the primary business and product goals using the SMART framework - Specific, Measurable, Achievable, Relevant, Time-bound.)*
### Success Criteria
*(Detail the quantifiable metrics, KPIs, or OKRs that will determine if this product launch is successful.)*

## Target Audience, Users & Personas
*(Detail the target audience demographics and psychographics. Provide 2-3 specific User Personas, including their background, goals, frustrations, and use cases.)*

## MVP Scope (In Scope / Out of Scope)
### In Scope (MVP)
*(Use bullet points to define exactly what features and capabilities MUST be delivered in this release.)*
### Out of Scope
*(Explicitly list features, integrations, or capabilities that are deliberately excluded from this release to prevent scope creep.)*

## User Stories & Use Cases
*(Provide detailed agile user stories for the core features. Format: "As a [type of user], I want to [perform some action] so that I can [achieve some goal]." Include Acceptance Criteria for each story.)*

## Functional Requirements
*(Break down the core features into explicit, testable system behaviors and functional requirements.)*

## Tools / Features Specification
*(Detail the specific tools, 3rd-party integrations, external APIs, or libraries required to make these features work.)*

## Technical Requirements
### Technology Stack
*(List the exact frontend, backend, database, and infrastructure technologies to be used.)*
### Core Architecture & System Design (incl. patterns)
*(Describe the architectural patterns - e.g., Microservices, Event-Driven, Monolith - and why they were chosen.)*
### System Architecture
*(Provide a structural overview of how the frontend, backend, database, and external services interact.)*
### Data Model
*(Define the high-level entity-relationship model, listing primary data entities and their relationships.)*
### API Specifications
*(Provide a Markdown table detailing the core REST/GraphQL endpoints required, including Method, Endpoint, and Purpose.)*

## UI/UX Requirements
*(Detail design system requirements, accessibility standards (e.g., WCAG AA), responsiveness targets, and core user flows.)*

## Security & Configuration Requirements
*(List authentication/authorization methods, data encryption (at rest and in transit), compliance needs (e.g., GDPR, SOC2), and environment configuration strategies.)*

## Performance Requirements
*(Define maximum acceptable latency, page load times, API response times, and target uptime/SLA.)*

## Scalability Requirements
*(Explain how the system should handle increased load, including concurrent user targets and database scaling strategies.)*

## Testing Strategy
*(Outline the approach for Unit Testing, Integration Testing, End-to-End (E2E) Testing, and User Acceptance Testing (UAT).)*

## Deployment Strategy
*(Describe the CI/CD pipeline, environment progression (Dev -> Staging -> Prod), and release strategies like feature flags or canary rollouts.)*

## Monitoring & Maintenance
*(List the tools and strategies for logging, error tracking, performance monitoring, and incident alerting.)*

## Documentation Requirements
*(Specify the required documentation deliverables, such as API docs, user manuals, and system architecture diagrams.)*

## Timeline, Milestones & Implementation Phases
*(Break down the development lifecycle into specific phases - e.g., Discovery, Design, Alpha, Beta, GA - with estimated timelines based on user input.)*

## Budget & Resources
*(Detail the required team topology - e.g., 2 Frontend, 1 Backend, 1 QA - and align with the user's provided budget/resource constraints.)*

## Risks & Mitigation
*(Provide a Markdown table of potential project risks (Technical, Schedule, Scope) along with their Impact, Probability, and a specific Mitigation Strategy.)*

## Future Considerations / Roadmap
*(List the features, enhancements, and technical debt items reserved for V2, V3, or future roadmap consideration.)*

---
**CRITICAL INSTRUCTION**: Do not omit any sections. Write the complete PRD now, populating each of the modules above with rich, professional, and contextually accurate product management content based on the user's inputs. Format beautifully with Markdown tables, bold text, and lists where appropriate.
  `;
}
