export interface ImageAttachment {
  id: string;
  file: File;
  preview: string;
  name: string;
  size: number;
  type: string;
  uploadedAt: Date;
}

export type ProductMode =
  | 'SaaS Product'
  | 'AI Product'
  | 'Mobile App'
  | 'Feature Enhancement';

export interface PrdInput {
  productName: string;
  targetAudience: string;
  problemStatement: string;
  proposedSolution: string;
  coreFeatures: string;
  keyFeatures: string;
  businessGoals: string;
  successMetrics: string;
  futureFeatures: string;
  techStack: string;
  constraints: string;
  timeline: string;
  budget: string;
  productMode: ProductMode;
  currentState?: string;
  proposedChanges?: string;
  productIdeaImages?: ImageAttachment[];
}

export const DEFAULT_PRD_INPUT: PrdInput = {
  productName: '',
  targetAudience: '',
  problemStatement: '',
  proposedSolution: '',
  coreFeatures: '',
  keyFeatures: '',
  businessGoals: '',
  successMetrics: '',
  futureFeatures: '',
  techStack: '',
  constraints: '',
  timeline: '',
  budget: '',
  productMode: 'SaaS Product',
  currentState: '',
  proposedChanges: '',
  productIdeaImages: []
};

export const SECTION_FIELD_MAPPING: Record<string, Array<keyof PrdInput>> = {
  '1. Core Product Idea': [
    'productName',
    'problemStatement',
    'proposedSolution'
  ],
  '2. Enhancement Scope': ['currentState', 'proposedChanges'],
  '3. Audience & Market': ['targetAudience', 'businessGoals', 'successMetrics'],
  '4. Features & Scope': ['coreFeatures', 'keyFeatures', 'futureFeatures'],
  '5. Technical Details': ['techStack', 'constraints'],
  '6. Planning & Execution': ['timeline', 'budget', 'constraints']
};

export function generatePreviewMarkdown(inputs: PrdInput): string {
  return `
# ${inputs.productName || 'Product Name...'}

*This is a live preview of your input. The final PRD will be generated by AI based on these details.*

### Problem Statement
${inputs.problemStatement || '...'}

### Proposed Solution
${inputs.proposedSolution || '...'}

### Target Audience
${inputs.targetAudience || '...'}

### Core Features
${inputs.coreFeatures || '...'}
  `;
}

export function buildGenerationPrompt(inputs: PrdInput): string {
  // Build image context if images are provided
  let imageContext = '';
  if (inputs.productIdeaImages && inputs.productIdeaImages.length > 0) {
    imageContext =
      '\n\n**Visual Context:** The user has provided the following images to help illustrate the product concept:\n';
    inputs.productIdeaImages.forEach((img, index) => {
      imageContext += `\n${index + 1}. ${img.name} (${img.type})\n`;
      imageContext += `   [Image data included for context - may contain mockups, wireframes, diagrams, or reference photos]\n`;
    });
    imageContext +=
      "\nPlease consider these visual materials when writing the PRD. They provide important context about the user's vision for the product design, user interface, and functionality.";
  }

  const isEnhancement = inputs.productMode === 'Feature Enhancement';
  const enhancementSection = isEnhancement
    ? `
**Input Context: Feature Enhancement**
* Current State (Before): ${inputs.currentState || 'Not specified.'}
* Proposed Changes (After): ${inputs.proposedChanges || 'Not specified.'}
`
    : '';

  return `
You are an expert Senior Product Manager at a leading tech company. Your task is to write a highly detailed, comprehensive Product Requirements Document (PRD) for a **${inputs.productMode}**.

The PRD MUST strictly follow the exact 29-module structure outlined below. Expand on the provided user inputs to create a robust, development-ready document. Extrapolate intelligently where necessary. Use professional formatting, bullet points, tables, and bold text where appropriate.

**Input Context from User:**
* Product Name: ${inputs.productName}
* Product Category: ${inputs.productMode}
* Problem Statement: ${inputs.problemStatement}
* Proposed Solution: ${inputs.proposedSolution}
${enhancementSection}
* Target Audience: ${inputs.targetAudience}
* Business Goals: ${inputs.businessGoals}
* Success Metrics: ${inputs.successMetrics}
* Core Features: ${inputs.coreFeatures}
* Key Differentiators: ${inputs.keyFeatures}
* Future Features: ${inputs.futureFeatures}
* Tech Stack: ${inputs.techStack}
* Timeline: ${inputs.timeline}
* Budget: ${inputs.budget}
* Constraints: ${inputs.constraints}
${imageContext}

**REQUIRED PRD STRUCTURE (Generate content for ALL these sections explicitly using these exact Markdown headings):**

# ${inputs.productName || 'Product Requirements Document'}

## Executive Summary
(Provide a high-level overview of the entire PRD)

## Project Overview
### Mission & Core Principles
### Problem Statement
### Goals & Objectives
### Success Criteria

## Target Audience, Users & Personas
(Detail the target audience and provide 2-3 specific user personas with examples)

## MVP Scope (In Scope / Out of Scope)
### In Scope (MVP)
### Out of Scope

## User Stories & Use Cases
(Provide detailed user stories with examples in the format: As a [user], I want [action], so that [benefit])

## Functional Requirements

## Tools / Features Specification

## Technical Requirements
### Technology Stack
### Core Architecture & System Design (incl. patterns)
### System Architecture
### Data Model
### API Specifications

## UI/UX Requirements

## Security & Configuration Requirements

## Performance Requirements

## Scalability Requirements

## Testing Strategy

## Deployment Strategy

## Monitoring & Maintenance

## Documentation Requirements

## Timeline, Milestones & Implementation Phases

## Budget & Resources

## Risks & Mitigation

## Future Considerations / Roadmap

Write the complete PRD now, populating each of the modules above with rich, professional, and contextually accurate product management content based on the user's inputs. Do not omit any sections.
  `;
}
